repos:
-   repo: local
    hooks:
    -   id: auto-format
        name: Auto-format Code
        entry: bash -c "dotnet format CddOpenApi.slnx"
        language: system
        pass_filenames: false

    -   id: format-check
        name: Check Code Formatting
        entry: bash -c "dotnet format CddOpenApi.slnx --verify-no-changes"
        language: system
        pass_filenames: false

    -   id: lint
        name: Lint (Analyzers)
        entry: bash -c "dotnet format analyzers CddOpenApi.slnx --verify-no-changes"
        language: system
        pass_filenames: false

    -   id: build
        name: Build
        entry: dotnet build CddOpenApi.slnx
        language: system
        pass_filenames: false

    -   id: tests-and-coverage
        name: Run tests and update coverage badges
        entry: bash scripts/update_badges.sh
        language: system
        pass_filenames: false
