repos:
-   repo: local
    hooks:
    -   id: tests-and-coverage
        name: Run tests and update coverage badges
        entry: bash -c "make test && bash scripts/update_badges.sh"
        language: system
        pass_filenames: false
